{
 "title": "Message Director",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Message Director Participants",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "md_participants_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Message Director Subscribers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "md_subscribers_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Message Director Observed Datagrams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "md_observed_datagrams_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Message Director Handled Datagrams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "md_handled_datagrams_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Message Director Datagrams Size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "increase(md_datagrams_bytes_size_bucket[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}